// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.3
// source: pb.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoomEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//
	//	*RoomEvent_AddUser_
	//	*RoomEvent_RemoveUser_
	//	*RoomEvent_ReorderUser_
	//	*RoomEvent_UpdateUserName_
	//	*RoomEvent_UpdateRoomName_
	//	*RoomEvent_MarkUserAbsent_
	//	*RoomEvent_MarkUserPresent_
	//	*RoomEvent_Undo_
	//	*RoomEvent_Redo_
	Event isRoomEvent_Event `protobuf_oneof:"Event"`
}

func (x *RoomEvent) Reset() {
	*x = RoomEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent) ProtoMessage() {}

func (x *RoomEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent.ProtoReflect.Descriptor instead.
func (*RoomEvent) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0}
}

func (m *RoomEvent) GetEvent() isRoomEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *RoomEvent) GetAddUser() *RoomEvent_AddUser {
	if x, ok := x.GetEvent().(*RoomEvent_AddUser_); ok {
		return x.AddUser
	}
	return nil
}

func (x *RoomEvent) GetRemoveUser() *RoomEvent_RemoveUser {
	if x, ok := x.GetEvent().(*RoomEvent_RemoveUser_); ok {
		return x.RemoveUser
	}
	return nil
}

func (x *RoomEvent) GetReorderUser() *RoomEvent_ReorderUser {
	if x, ok := x.GetEvent().(*RoomEvent_ReorderUser_); ok {
		return x.ReorderUser
	}
	return nil
}

func (x *RoomEvent) GetUpdateUserName() *RoomEvent_UpdateUserName {
	if x, ok := x.GetEvent().(*RoomEvent_UpdateUserName_); ok {
		return x.UpdateUserName
	}
	return nil
}

func (x *RoomEvent) GetUpdateRoomName() *RoomEvent_UpdateRoomName {
	if x, ok := x.GetEvent().(*RoomEvent_UpdateRoomName_); ok {
		return x.UpdateRoomName
	}
	return nil
}

func (x *RoomEvent) GetMarkUserAbsent() *RoomEvent_MarkUserAbsent {
	if x, ok := x.GetEvent().(*RoomEvent_MarkUserAbsent_); ok {
		return x.MarkUserAbsent
	}
	return nil
}

func (x *RoomEvent) GetMarkUserPresent() *RoomEvent_MarkUserPresent {
	if x, ok := x.GetEvent().(*RoomEvent_MarkUserPresent_); ok {
		return x.MarkUserPresent
	}
	return nil
}

func (x *RoomEvent) GetUndo() *RoomEvent_Undo {
	if x, ok := x.GetEvent().(*RoomEvent_Undo_); ok {
		return x.Undo
	}
	return nil
}

func (x *RoomEvent) GetRedo() *RoomEvent_Redo {
	if x, ok := x.GetEvent().(*RoomEvent_Redo_); ok {
		return x.Redo
	}
	return nil
}

type isRoomEvent_Event interface {
	isRoomEvent_Event()
}

type RoomEvent_AddUser_ struct {
	AddUser *RoomEvent_AddUser `protobuf:"bytes,1,opt,name=add_user,json=addUser,proto3,oneof"`
}

type RoomEvent_RemoveUser_ struct {
	RemoveUser *RoomEvent_RemoveUser `protobuf:"bytes,2,opt,name=remove_user,json=removeUser,proto3,oneof"`
}

type RoomEvent_ReorderUser_ struct {
	ReorderUser *RoomEvent_ReorderUser `protobuf:"bytes,3,opt,name=reorder_user,json=reorderUser,proto3,oneof"`
}

type RoomEvent_UpdateUserName_ struct {
	UpdateUserName *RoomEvent_UpdateUserName `protobuf:"bytes,4,opt,name=updateUserName,proto3,oneof"`
}

type RoomEvent_UpdateRoomName_ struct {
	UpdateRoomName *RoomEvent_UpdateRoomName `protobuf:"bytes,5,opt,name=updateRoomName,proto3,oneof"`
}

type RoomEvent_MarkUserAbsent_ struct {
	MarkUserAbsent *RoomEvent_MarkUserAbsent `protobuf:"bytes,6,opt,name=markUserAbsent,proto3,oneof"`
}

type RoomEvent_MarkUserPresent_ struct {
	MarkUserPresent *RoomEvent_MarkUserPresent `protobuf:"bytes,7,opt,name=markUserPresent,proto3,oneof"`
}

type RoomEvent_Undo_ struct {
	Undo *RoomEvent_Undo `protobuf:"bytes,8,opt,name=undo,proto3,oneof"`
}

type RoomEvent_Redo_ struct {
	Redo *RoomEvent_Redo `protobuf:"bytes,9,opt,name=redo,proto3,oneof"`
}

func (*RoomEvent_AddUser_) isRoomEvent_Event() {}

func (*RoomEvent_RemoveUser_) isRoomEvent_Event() {}

func (*RoomEvent_ReorderUser_) isRoomEvent_Event() {}

func (*RoomEvent_UpdateUserName_) isRoomEvent_Event() {}

func (*RoomEvent_UpdateRoomName_) isRoomEvent_Event() {}

func (*RoomEvent_MarkUserAbsent_) isRoomEvent_Event() {}

func (*RoomEvent_MarkUserPresent_) isRoomEvent_Event() {}

func (*RoomEvent_Undo_) isRoomEvent_Event() {}

func (*RoomEvent_Redo_) isRoomEvent_Event() {}

type EventMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt uint64 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{1}
}

func (x *EventMetadata) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventMetadata) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *EventMetadata) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RoomEventWithMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *EventMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Event    *RoomEvent     `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
}

func (x *RoomEventWithMetadata) Reset() {
	*x = RoomEventWithMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEventWithMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEventWithMetadata) ProtoMessage() {}

func (x *RoomEventWithMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEventWithMetadata.ProtoReflect.Descriptor instead.
func (*RoomEventWithMetadata) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{2}
}

func (x *RoomEventWithMetadata) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RoomEventWithMetadata) GetEvent() *RoomEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type RoomEvent_AddUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Order  float64 `protobuf:"fixed64,3,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *RoomEvent_AddUser) Reset() {
	*x = RoomEvent_AddUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_AddUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_AddUser) ProtoMessage() {}

func (x *RoomEvent_AddUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_AddUser.ProtoReflect.Descriptor instead.
func (*RoomEvent_AddUser) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RoomEvent_AddUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomEvent_AddUser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomEvent_AddUser) GetOrder() float64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type RoomEvent_RemoveUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RoomEvent_RemoveUser) Reset() {
	*x = RoomEvent_RemoveUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_RemoveUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_RemoveUser) ProtoMessage() {}

func (x *RoomEvent_RemoveUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_RemoveUser.ProtoReflect.Descriptor instead.
func (*RoomEvent_RemoveUser) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RoomEvent_RemoveUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomEvent_ReorderUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Order  float64 `protobuf:"fixed64,2,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *RoomEvent_ReorderUser) Reset() {
	*x = RoomEvent_ReorderUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_ReorderUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_ReorderUser) ProtoMessage() {}

func (x *RoomEvent_ReorderUser) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_ReorderUser.ProtoReflect.Descriptor instead.
func (*RoomEvent_ReorderUser) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RoomEvent_ReorderUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomEvent_ReorderUser) GetOrder() float64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type RoomEvent_UpdateUserName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RoomEvent_UpdateUserName) Reset() {
	*x = RoomEvent_UpdateUserName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_UpdateUserName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_UpdateUserName) ProtoMessage() {}

func (x *RoomEvent_UpdateUserName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_UpdateUserName.ProtoReflect.Descriptor instead.
func (*RoomEvent_UpdateUserName) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 3}
}

func (x *RoomEvent_UpdateUserName) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RoomEvent_UpdateUserName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoomEvent_UpdateRoomName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RoomEvent_UpdateRoomName) Reset() {
	*x = RoomEvent_UpdateRoomName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_UpdateRoomName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_UpdateRoomName) ProtoMessage() {}

func (x *RoomEvent_UpdateRoomName) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_UpdateRoomName.ProtoReflect.Descriptor instead.
func (*RoomEvent_UpdateRoomName) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 4}
}

func (x *RoomEvent_UpdateRoomName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RoomEvent_MarkUserAbsent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RoomEvent_MarkUserAbsent) Reset() {
	*x = RoomEvent_MarkUserAbsent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_MarkUserAbsent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_MarkUserAbsent) ProtoMessage() {}

func (x *RoomEvent_MarkUserAbsent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_MarkUserAbsent.ProtoReflect.Descriptor instead.
func (*RoomEvent_MarkUserAbsent) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 5}
}

func (x *RoomEvent_MarkUserAbsent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomEvent_MarkUserPresent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *RoomEvent_MarkUserPresent) Reset() {
	*x = RoomEvent_MarkUserPresent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_MarkUserPresent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_MarkUserPresent) ProtoMessage() {}

func (x *RoomEvent_MarkUserPresent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_MarkUserPresent.ProtoReflect.Descriptor instead.
func (*RoomEvent_MarkUserPresent) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 6}
}

func (x *RoomEvent_MarkUserPresent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RoomEvent_Undo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *RoomEvent_Undo) Reset() {
	*x = RoomEvent_Undo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_Undo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_Undo) ProtoMessage() {}

func (x *RoomEvent_Undo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_Undo.ProtoReflect.Descriptor instead.
func (*RoomEvent_Undo) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 7}
}

func (x *RoomEvent_Undo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type RoomEvent_Redo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *RoomEvent_Redo) Reset() {
	*x = RoomEvent_Redo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoomEvent_Redo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomEvent_Redo) ProtoMessage() {}

func (x *RoomEvent_Redo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomEvent_Redo.ProtoReflect.Descriptor instead.
func (*RoomEvent_Redo) Descriptor() ([]byte, []int) {
	return file_pb_proto_rawDescGZIP(), []int{0, 8}
}

func (x *RoomEvent_Redo) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_pb_proto protoreflect.FileDescriptor

var file_pb_proto_rawDesc = []byte{
	0x0a, 0x08, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x22, 0xd4, 0x08, 0x0a, 0x09, 0x52, 0x6f,
	0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x0a, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x49,
	0x0a, 0x0c, 0x72, 0x65, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69,
	0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52,
	0x65, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0b, 0x72, 0x65,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x51, 0x0a, 0x0e, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75,
	0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x51, 0x0a, 0x0e,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69,
	0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x48, 0x00, 0x52,
	0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x51, 0x0a, 0x0e, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x62, 0x73, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e,
	0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74,
	0x48, 0x00, 0x52, 0x0e, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x62, 0x73, 0x65,
	0x6e, 0x74, 0x12, 0x54, 0x0a, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x65, 0x73, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x6d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x33, 0x0a, 0x04, 0x75, 0x6e, 0x64, 0x6f,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x2e, 0x55, 0x6e, 0x64, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x75, 0x6e, 0x64, 0x6f, 0x12, 0x33, 0x0a,
	0x04, 0x72, 0x65, 0x64, 0x6f, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x64, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x72, 0x65,
	0x64, 0x6f, 0x1a, 0x4c, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x1a, 0x25, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x3c, 0x0a, 0x0b, 0x52, 0x65, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x1a, 0x3d, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x24, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x29, 0x0a, 0x0e, 0x4d, 0x61,
	0x72, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x62, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x2a, 0x0a, 0x0f, 0x4d, 0x61, 0x72, 0x6b, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x1a, 0x21, 0x0a, 0x04, 0x55, 0x6e, 0x64, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x1a, 0x21, 0x0a, 0x04, 0x52, 0x65, 0x64, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0x5d, 0x0a, 0x0d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22,
	0x81, 0x01, 0x0a, 0x15, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x38, 0x0a, 0x08, 0x6d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x65,
	0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65, 0x75, 0x70, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x2e, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x6c, 0x69, 0x6e, 0x65,
	0x75, 0x70, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pb_proto_rawDescOnce sync.Once
	file_pb_proto_rawDescData = file_pb_proto_rawDesc
)

func file_pb_proto_rawDescGZIP() []byte {
	file_pb_proto_rawDescOnce.Do(func() {
		file_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_proto_rawDescData)
	})
	return file_pb_proto_rawDescData
}

var file_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_proto_goTypes = []interface{}{
	(*RoomEvent)(nil),                 // 0: meetinglineup.RoomEvent
	(*EventMetadata)(nil),             // 1: meetinglineup.EventMetadata
	(*RoomEventWithMetadata)(nil),     // 2: meetinglineup.RoomEventWithMetadata
	(*RoomEvent_AddUser)(nil),         // 3: meetinglineup.RoomEvent.AddUser
	(*RoomEvent_RemoveUser)(nil),      // 4: meetinglineup.RoomEvent.RemoveUser
	(*RoomEvent_ReorderUser)(nil),     // 5: meetinglineup.RoomEvent.ReorderUser
	(*RoomEvent_UpdateUserName)(nil),  // 6: meetinglineup.RoomEvent.UpdateUserName
	(*RoomEvent_UpdateRoomName)(nil),  // 7: meetinglineup.RoomEvent.UpdateRoomName
	(*RoomEvent_MarkUserAbsent)(nil),  // 8: meetinglineup.RoomEvent.MarkUserAbsent
	(*RoomEvent_MarkUserPresent)(nil), // 9: meetinglineup.RoomEvent.MarkUserPresent
	(*RoomEvent_Undo)(nil),            // 10: meetinglineup.RoomEvent.Undo
	(*RoomEvent_Redo)(nil),            // 11: meetinglineup.RoomEvent.Redo
}
var file_pb_proto_depIdxs = []int32{
	3,  // 0: meetinglineup.RoomEvent.add_user:type_name -> meetinglineup.RoomEvent.AddUser
	4,  // 1: meetinglineup.RoomEvent.remove_user:type_name -> meetinglineup.RoomEvent.RemoveUser
	5,  // 2: meetinglineup.RoomEvent.reorder_user:type_name -> meetinglineup.RoomEvent.ReorderUser
	6,  // 3: meetinglineup.RoomEvent.updateUserName:type_name -> meetinglineup.RoomEvent.UpdateUserName
	7,  // 4: meetinglineup.RoomEvent.updateRoomName:type_name -> meetinglineup.RoomEvent.UpdateRoomName
	8,  // 5: meetinglineup.RoomEvent.markUserAbsent:type_name -> meetinglineup.RoomEvent.MarkUserAbsent
	9,  // 6: meetinglineup.RoomEvent.markUserPresent:type_name -> meetinglineup.RoomEvent.MarkUserPresent
	10, // 7: meetinglineup.RoomEvent.undo:type_name -> meetinglineup.RoomEvent.Undo
	11, // 8: meetinglineup.RoomEvent.redo:type_name -> meetinglineup.RoomEvent.Redo
	1,  // 9: meetinglineup.RoomEventWithMetadata.metadata:type_name -> meetinglineup.EventMetadata
	0,  // 10: meetinglineup.RoomEventWithMetadata.event:type_name -> meetinglineup.RoomEvent
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pb_proto_init() }
func file_pb_proto_init() {
	if File_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEventWithMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_AddUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_RemoveUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_ReorderUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_UpdateUserName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_UpdateRoomName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_MarkUserAbsent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_MarkUserPresent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_Undo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoomEvent_Redo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pb_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RoomEvent_AddUser_)(nil),
		(*RoomEvent_RemoveUser_)(nil),
		(*RoomEvent_ReorderUser_)(nil),
		(*RoomEvent_UpdateUserName_)(nil),
		(*RoomEvent_UpdateRoomName_)(nil),
		(*RoomEvent_MarkUserAbsent_)(nil),
		(*RoomEvent_MarkUserPresent_)(nil),
		(*RoomEvent_Undo_)(nil),
		(*RoomEvent_Redo_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_proto_goTypes,
		DependencyIndexes: file_pb_proto_depIdxs,
		MessageInfos:      file_pb_proto_msgTypes,
	}.Build()
	File_pb_proto = out.File
	file_pb_proto_rawDesc = nil
	file_pb_proto_goTypes = nil
	file_pb_proto_depIdxs = nil
}

// md5-hash 997514e4b774008ebac67a7c7a0f758d
